import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Providers from "@/providers/PrivyWrapper";
import Navbar from "@/Components/Navbar/Navbar";
import localFont from 'next/font/local'

const neuebit = localFont({
  src: '/fonts/ppneuebit-bold.otf', 
  display: 'swap',
  variable: '--font-neuebit'
})


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${neuebit.variable} antialiased`}
      >
        <Providers>
          <Navbar/>
          {children}
          </Providers>
      </body>
    </html>
  );
}
